
export const SIGN_UP = '/SignUpPage'
export const SIGN_IN = '/'
export const HOME = '/home'
export const FORUM = '/forum'
export const ACCOUNT = '/account'
export const ADMIN = '/admin'
export const PASSWORD_FORGET = '/passwordForget'
export const COMUNITY = '/comunity'
export const MYPROFILE = '/myProfile'
export const ADMIN_DETAILS = '/admin/:id'
